import type { Metadata } from "next";
import { Signika, Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/footer";

const signika = Signika({
  variable: "--font-signika",
  subsets: ["latin"],
  display: "swap",
});

const montse = Montserrat({
  variable: "--font-montse",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Nepalese Sultan Butchers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${signika.variable}
          ${montse.variable}
          antialiased
        `}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
